UI-1 Added full text search with lunr
arcanite24/deimos-blog pull request #1
Opened 2020-07-20 00:41 UTC by arcanite24

> Added full text search for all the blog posts using lunr.js

Technical Details:
- We generate the index cache at build time using Gatsby own NodeJS pipeline (under /gatsby-node.js)
- We're only indexing the title and an excerpt of max 500 characters
- The cache is saved to /static/idx.json then at build time copied to /public/idx.json
- The cache is accesible by anyone under blog.deimos.app/idx.json

2020-07-20 03:13 UTC, ElZombieIsra requested changes
Overall changes and code styling

2020-07-20 03:13 UTC, ElZombieIsra commented on gatsby-node.js
> +  fs.writeFileSync(
Wrap in a "writeFile" util function?

2020-07-20 03:13 UTC, ElZombieIsra commented on gatsby-node.js
> +      _this.add({
For-of/for-in/for to avoid creating _this wrapper?

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/layout.js
> +          .map(p => ({
More descriptive variables names

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/layout.js
> +          .reduce((acc, curr) => ({ ...acc, ...curr }), {})}
Same

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +const GlobalSearch = ({ placeholder = 'Search something', posts }) => {
Are we going to use localizations? If so, we need to map these strings ASAP so they won't become a pain to map later

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +  const upPressed = useKeyPress(['ArrowUp']);
Maybe write these names into an enum so they won't be misspelled in the future.

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +      const newIndex = currentIndex > 0 ? currentIndex - 1 : results.length - 1;
Maybe wrap this logic in a "changeIndex" function to make it cleaner?

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +      const newIndex = currentIndex < results.length - 1 ? currentIndex + 1 : 0;
Same as above

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +const DEBOUNCE_DELAY = 300;
Isn't it better a 1000ms debounce delay time?
Append metric time name to variable name ex: `DEBOUNCE_TIME_IN_MILLISECONDS`

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +      const actualPost = results[currentIndex];
Actual or current post?

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +        ...foundPosts.map(p => ({
Var names

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +          slug: 'asdasdasd',
Hardcoded post? Fetch from somewhere else

2020-07-20 03:13 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +      setSelected(foundPosts[0]?.ref);
Is it safe to use null safety operators in js?

2020-07-20 03:13 UTC, ElZombieIsra commented on src/pages/index.js
> -      {/* <p>{JSON.stringify(posts)}</p>
Remove not used code to avoid trash and improve readability

2020-07-20 22:40 UTC, arcanite24 commented on src/components/layout.js
> +          .map(p => ({
change to .post

2020-07-20 22:41 UTC, arcanite24 commented on src/components/search/GlobalSearch.jsx
> +const GlobalSearch = ({ placeholder = 'Search something', posts }) => {
No we're not using i18n

2020-07-20 22:41 UTC, arcanite24 commented on src/components/search/GlobalSearch.jsx
> +const DEBOUNCE_DELAY = 300;
300 for UX seems ok

2020-07-22 18:51 UTC, arcanite24 commented on gatsby-node.js
> +      _this.add({
Tested with normal for and Lunr required forEach :$ keeping this for now

2020-07-22 19:12 UTC, ElZombieIsra approved these changes
Parece basura para mi

2020-07-22 19:12 UTC, ElZombieIsra commented on gatsby-node.js
> +};
Abstract to a utils folder. Approving for now.

2020-07-22 19:12 UTC, ElZombieIsra commented on gatsby-node.js
> +      _this.add({
Lil sus, but ok

2020-07-22 19:12 UTC, ElZombieIsra commented on src/components/search/GlobalSearch.jsx
> +const DEBOUNCE_DELAY = 300;
Const name didn't change(?),

2020-07-22 19:15 UTC, merged